### PR TITLE
Use recursion for finding sub domains

### PR DESCRIPTION
**Pull request by stojg**
> Don't communicate by sharing memory; share memory by communicating.
> - Rob Pike

Use channels as a way of limiting number of threads so that we can use recursion

### CODE REVIEW

**Comment by stojg** [comment]
Oh, please hold, there are some yucke edge cases and speed improvements that needs to be done

**Comment by ss23** [comment]
This has a race condition, the obvious one I was trying to avoid in my complicated code.

Consider the case where the last line in the wordlist is a domain that resolves, and that resolving takes 1000ms (for the sake of argument).
All other threads finish, they then signal .Done(), and finish execution.
The last thread then adds 50k more items to be processed, but it is the only thread left executing. No performance -> death.

I am unsure if this can be resolved with a style of threading like this, but it is the primary reason for the complicated code I've written.

**Comment by stojg** [comment]
yeah, It seems hard. I though about pipelines feeding in at the top again, but that would still not work due the the pipeline pattern relies on closing channels when work is done.

My latest idea is to use plain old recursion, and using channels to limit and syncronise workers. Not sure how good the approach is.

I also noticed the wildcard detection and tried to find a easy way of detecting it, feels slightly silly to check random subdomains, but no dice so far.

**Comment by stojg** [comment]
~And TBH, the wildcard detection isn't working that in this code.~ reverted to your implementation. Feel free to close or copy/pasta pieces if it's useful

**Comment by ss23** [comment]
Debugging a somewhat strange issue with this. Not sure yet if it's a problem with the code or not, but:
```
ss23@crisp ~/glugger $ ./main -domain ss23.geek.nz -threads 1000
Detected wildcard record
st.ss23.geek.nz
home.ss23.geek.nz
```
The original works fine at 1000 threads, but:
```
ss23@crisp ~/glugger-stig $ go run main.go -domain ss23.geek.nz -threads 100
Detected wildcard record
st.ss23.geek.nz [45.79.98.172]
home.ss23.geek.nz [210.54.35.24]
^Csignal: interrupt
ss23@crisp ~/glugger-stig $ go run main.go -domain ss23.geek.nz -threads 1000
Detected wildcard record
ss23@crisp ~/glugger-stig $
```

Hopefully you can see by this, when you get up to 1000 threads, the code seems to stop printing anything out. If it was purely network, I might expect it to happen with the original implementation too, so might be some kind of issue with exiting too soon to print or similar?

**Comment by stojg** [comment]
Maybe it's is a race condition with the array and book holding the wildcard.

I can have a look later with -race and that number of threads

**Comment by stojg** [comment]
Could also be that the program quits before the output can be sent to the
terminal.. concurrency is still hard :)

**Comment by ss23** [comment]
Looks like it's just an issue with opening too many sockets. Doing a little more investigation to be sure but it looks fine to me generally.

**Pull request merged**
